### PR TITLE
Changed Second Montgomery constant to a more suitable value

### LINKED ISSUE #32: "Drum" word duping in generated SSKR shares
I tried to generate SSKR phrases with the app and they are looking weird. All of them except first one just contains repeated "Drum" word in positions from 11 to 42 (I believe other words just  contains meta information and checksums). And for sure, I can't recover my bip39 phrase from this SSKR shares. My Seed phrace contains 24 words but to create this issue I generated a new one. I tried to use this shares to recover my seed phrase using [seedtool-cli](https://github.com/BlockchainCommons/seedtool-cli) but for sure got error that shares are invalid 

1. Reset Ledger Nano S+ by next 24 words seed phrase (it's new generated one don't worry)
```
head bulb beauty miracle vessel kick toddler bamboo defense open hill fiscal feature illness fence reunion hub song glory occur cannon enjoy wasp common
```
2. Install the Seed App 
3. Open Seed App
4. Select "Check BIP39 phase" 
5. Select "24 words"
6. Input the seed phrase and complete check
7. Select number of shares - 6
8. Select number of threshold - 3
9. Get the list of shares 
```
1. tuna acid epic hard data axis whiz able also able yurt poem iron note idle vast quiz when each zone unit curl twin quiz navy aunt dice whiz onyx skew yurt meow visa tuna calm fuel  whiz purr cola cola legs hang able able numb frog
2. tuna acid epic hard data axis whiz able also acid drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able oval flux
3. tuna acid epic hard data axis whiz able also also drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able vows calm
4. tuna acid epic hard data axis whiz able also apex drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able jazz jowl
5. tuna acid epic hard data axis whiz able also aqua drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able fuel draw
6. tuna acid epic hard data axis whiz able also arch drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able scar gyro
```
10. Check seed phrace back using seedtool-cli
```
docker run --rm -it seedtool-cli -i sskr
tuna acid epic hard data axis whiz able also apex drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able jazz jowl
tuna acid epic hard data axis whiz able also aqua drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able fuel draw
tuna acid epic hard data axis whiz able also arch drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum drum able able scar gyro
^D
seedtool: Invalid Bytewords.
```

Device:
 - Device: Ledger Nano S+
 - Firmware version: 1.1.1
 - App Version v1.7.1 
 - Free Space on device: 539 Kb

### PR DESCRIPTION
**Pull request by aido**
# Checklist

- [x] App update process has been followed 
- [x] Target branch is `develop` 
- [x] Application version has been bumped 

On advice from @srasoamiaramanana-ledger on Ledger's Discord channel 0x02 is a more suitable value for the Second Montgomery constant used by `cx_bn_gf2_n_mul()`. This PR makes that change.

Hopefully this will fix aido/app-seed-tool#32.

### CODE REVIEW

**Comment by aido** [comment]
Hi,

I am still a bit confused over how the Second Montgomery constant is calculated for the irreducible polynomial x^8 + x^4 + x^3 + x + 1 .

@srasoamiaramanana-ledger has said on Discord that the Second Montgomery constant = x^(2*128) mod x^8 + x^4 + x^3 + x + 1 = **0x02**.

However, when I do same calculation I get the following result.

x^8 + x^4 + x^3 + x + 1 = 0x11B = 283
Second Montgomery constant = x^(2 * 128) mod x^8 + x^4 + x^3 + x + 1 = x^256 mod 283 = 161 = **0xA1**

Obviously 0x02 ≠ 0xA1. We both seem to be doing the same calculation but get different results.
0xA1 was the value I was originally using for the bn_h parameter of the `cx_bn_gf2_n_mul()` syscall.

Due to this discrepancy I will leave this PR in draft status until I get a definitive answer.

**Comment by srasoamiaramanana-ledger** [comment]
Hi,
If I understand correctly how you end up with 0xA1, you compute `2^256 mod 283` by taking the binary representation of `x^256` and  `x^8 + x^4 + x^3 + x + 1` and then using the hexadecimal numbers. By doing so, it's like you're are doing the operation in the finite field GF(283) but it's not the same as doing the operation in GF(2^8) (which is what we want to do) because these fields are not isomorphic. You can see that GF(283) has 283 elements and GF(2^8) has 256 elements. That's why we don't get the same result.
If you're familiar with sagemath, this is what I've done:
`F2 = GF(2)`
`R.<x> = PolynomialRing(F2)` (define the polynomial ring over GF(2))
`F = F2.extension(x^8+x^4+x^3+x+1, 'a')` (define the GF(2) extension of degree 8  = GF(2^8), elements will be expressed with the variable 'a')
`F(x^256)` (compute the element of F which corresponds to x^256 mod x^8+x^4+x^3+x+1)
The last command prints `a` which is `10` in binary representation.

**Comment by aido** [comment]
Hi @srasoamiaramanana-ledger,

Thank you for your detailed and convincing response.
This PR is now ready for review.

**Comment by aido** [comment]
Hi yet again @srasoamiaramanana-ledger,

I've been playing with SageMath,

```
F2 = GF(2)
R.<x> = PolynomialRing(F2)
F = F2.extension(x^8+x^4+x^3+x+1, 'a')
F(x^256)
```
The last command does indeed print `a` which is `10` in binary representation.

But

```
F2 = GF(2)
R.<x> = PolynomialRing(F2)
F = F2.extension(x^8+x^4+x^3+x+1, 'TEST')
F(x^256)
```

Here the last command prints `TEST` ... which is the name I gave the F2.extension.
So the `a` you are getting in your calculation is a name not a value?

I think this code may also be of interest:

https://github.com/LedgerHQ/cylib/blob/8d628735af55e2481387beebd8a57a1f85bbae70/wrappers/bolos/cy_wrap_fp_bolos.c#L200-L249

I believe it also calculates a value of 0xA1 for the Second Montgomery constant but I need to confirm this.

PR is back in draft status again!  😃

**Comment by aido** [comment]
@srasoamiaramanana-ledger,

Does this SageMath make sense?

```
# Define the finite field of 2 elements
F2 = GF(2)

# Define the polynomial ring over F2
R.<x> = PolynomialRing(F2)

# Define the polynomial to create the field extension
f = x^8 + x^4 + x^3 + x + 1

# Create the field extension using the polynomial f
F.<a> = F2.extension(f)

# Compute a^256 in the field F
element = F(a^256)

# Convert the field element to its polynomial form
poly = element.polynomial()

# Get the binary representation as a string
binary_str = ''.join(str(int(c)) for c in poly.coefficients(sparse=False))

# Convert the binary string to an integer
binary_int = int(binary_str, 2)

# Convert the integer to a hexadecimal string
hex_str = hex(binary_int)

# Print the hexadecimal representation
print(hex_str)
```

This gives me `0x01`

**Comment by srasoamiaramanana-ledger** [comment]
> So the a you are getting in your calculation is a name not a value?

`F(x^256) = a` is an element of GF(2^8) and can be seen as a polynomial of degree 1 over the variable `a`, in the same way that `x^8 + x^4 + x^3 + x + 1` is a polynomial over the variable `x`. To be more precise, 'a' is the name of the generator of the field. May be `F(x^256) = 0 * a^7 + 0 * a^6 + 0 * a^5 + 0 * a^4 + 0 * a^3 + 0 * a^2 + 1 * a + 0 * 1` is clearer.
You have to choose the variable to express any element of the field, but the variable must be different from the variable you chose for the irreducible polynomial. If you choose 'test' as variable to express any element of GF(2^8) and try `F.random_element()` you get for example `test^6 + test^4 + test^3 + test` (`test` is just the variable to express the polynomial). So you can use t, y, z, ..., it doesn't matter.

> I believe it also calculates a value of 0xA1 for the Second Montgomery constant but I need to confirm this.

That's probably true because the code computes the Montgomery constant over a prime field GF(n) where n is a prime number, but not the Montgomery constant over GF(2^n).

> Does this SageMath make sense?

Yes but be careful with the endianness, that's why it prints 0x01.
For example
```
sage: e = F.random_element()
sage: e = e.polynomial()
sage: e
a^7 + a^6 + a^4 + a^2 + a
sage: e.coefficients(sparse=False)
[0, 1, 1, 0, 1, 0, 1, 1]
```

You can see that the first coefficient in the list is the coefficient of the degree-0 term (a), and the last coefficient in the list is the coefficient of the degree-7 term (a^7).

**Comment by aido** [comment]
OK, thanks yet again @srasoamiaramanana-ledger  for the even more detailed explanation.

PR ready for review AGAIN! 😃

**Comment by aido** [comment]
Hi @lpascal-ledger or @xchapron-ledger,

Is a review of this PR imminent? I am eager to have this app released,
The important change made in this PR is quite a simple one, a change of the value for the Second Montgomery constant.

**Comment by lpascal-ledger** [comment]
Uh sorry @aido I got distracted from this topic! :bow:  And unfortunately @xchapron-ledger is no longer part of the team :(

I triggered the CI, looks like some workflows are not fully happy with the code. 2 minor linting shenanigans but a more interesting issue with unit testing.
If I were picky I could also argue that you bumped the patch version (`1.7.2` -> `1.7.3`) while the `CHANGELOG.md` documents 3 `Changed` items, generally interpreted as updates or features (implying a minor version bump) rather than fixes.

But whatever these numbers, as soon as the CI's ok, I could merge & deploy again.

**Comment by aido** [comment]
> Uh sorry @aido I got distracted from this topic! 

No problem

I've fixed up most issues but that unit test fail is strange indeed, Currently investigating.

**Comment by aido** [comment]
Hi @lpascal-ledger,

It turns out that the cmocka git repo now rejects connections even when cloning manually:

```
aido@dev:/git$ git clone --branch cmocka-1.1.7 https://git.cryptomilk.org/projects/cmocka.git
Cloning into 'cmocka'...
fatal: the remote end hung up unexpectedly
```

I have changed CMake to now use https://gitlab.com/cmocka/cmocka.git instead.

In future, instead of using git, I may just download the cmocka tarball from cmocka.org.  But for now the unit tests are working again.

**Comment by lpascal-ledger** [comment]
@aido 1.7.3 version has been deployed

**Pull request merged**
