### PR TITLE
v1.7.4-rc.2 : Ensure result does not overlap with operands in calls to `cx_bn_gf2_n_mul()`

### PR DESCRIPTION
**Pull request by aido**
# Checklist

- [x] App update process has been followed 
- [x] Target branch is `develop` 
- [x] Application version has been bumped 

# Description
v1.7.4-rc.1 proved that the issue reported in aido/app-seed-tool#32 is related to how the `cx_bn_gf2_n_mul()` syscall is being used in the app. This PR now ensures that the result parameter passed to `cx_bn_gf2_n_mul()` is distinct from the operands and should fix the issue.

This is the second and hopefully last pre-release of v1.7.4.

> [!NOTE]
> Codecov action still fails. Briefly switched to codecov GitHub action v4 but that seems to now need `gpg` installed. ledger-app-builder does not have this so have switched back to v3 for now.

### CODE REVIEW

**Comment by aido** [comment]
@lpascal-ledger,

A gentle nudge to help push this PR along,

I am confident that this pre-release version will fix aido/app-seed-tool#32. Once merged and tested we may go to a fixed v1.7.4.

**Comment by aido** [comment]
Hi @lpascal-ledger,

Has v1.7.4-rc.2 been deployed on provider 4 yet? It does not seem to be showing up in Ledger Live, still v1.7.4-rc.1.

**Comment by lpascal-ledger** [comment]
Hey @aido,
The deployment is in progress, but it could take a few hours depending on CI parameters (tooling update, runners availability, ...) and/or because we generally wait for a minimal batch of apps to sign & release them fully. I'll notify you when it's complete.

**Comment by aido** [comment]
Nice one, thanks! 👍

**Comment by lpascal-ledger** [comment]
@aido 1.7.4-rc2 should be available now on provider 4.

**Pull request merged**
