### PR TITLE
1.7.4 final

### PR DESCRIPTION
**Pull request by aido**
# Checklist

- [x] App update process has been followed 
- [x] Target branch is `develop` 
- [x] Application version has been bumped 

# Description
This PR bumps the version of app-seed-tool to v1.7.4

v1.7.4 fixes issues aido/app-seed-tool#32 and aido/app-seed-tool#36.

While working on v1.7.4 the following was observed:

1. The documentation for the `cx_bn_gf2_n_mul()` syscall should probably be updated to state that the operands and result should not overlap. Maybe something similar to what is already documented for the BN bit manipulation syscalls:
https://github.com/LedgerHQ/ledger-secure-sdk/blob/c6d481025144ab2a57b904e98f796f3d5c1d83fc/include/ox_bn.h#L356

2. Perhaps this rule should even be enforced by changing:
https://github.com/LedgerHQ/ledger-secure-sdk/blob/c6d481025144ab2a57b904e98f796f3d5c1d83fc/src/syscalls.c#L638
to something like the following:
```C
return (r == a || r == b)
            ? CX_INVALID_PARAMETER
            : SVC_cx_call(SYSCALL_cx_bn_gf2_n_mul_ID, parameters);
```

3. The documentation for the `cx_bn_cnt_bits()` syscall is misleading. The documentation suggests that the syscall returns the number of bits set in a big number:
https://github.com/LedgerHQ/ledger-secure-sdk/blob/c6d481025144ab2a57b904e98f796f3d5c1d83fc/include/ox_bn.h#L495
This instead should probably state that the syscall returns the number of significant bits in a big number.
See https://github.com/LedgerHQ/speculos/issues/487#issuecomment-2112382178

I am not sure if an issue needs to be raised for each of these points

### CODE REVIEW

**Comment by aido** [comment]
Hi @lpascal-ledger,

To be getting ahead of myself slightly, if/when this PR is deemed good enough to be merged what is the next step or requirement to have v1.7.4  ready for a general release on provider 1?

**Comment by aido** [comment]
Hi @lpascal-ledger,

To be getting ahead of myself slightly, if/when this PR is deemed good enough to be merged what is the next step or requirement to have v1.7.4  ready for a general release on provider 1?

**Comment by aido** [comment]
Hi @lpascal-ledger, 

A chat with @vforgeoux-ledger on Discord informs me that this app is almost ready for a general release. If this PR is approved then Donjon can have a look and if all is OK we will be good to go.

**Comment by lpascal-ledger** [comment]
@aido merged, and a deployment on provider 4 (NanoZ) and 83 (Stax) is on its way.

Indeed Victor is the right person for stable release (everything going to provider 1) decision and more generally everything regarding application release process :+1:

**Pull request merged**
