### PR TITLE
 v1.7.4-rc.1 : Use internal `bn_gf2_n_mul()`  function instead of `cx_bn_gf2_n_mul()` syscall

### PR DESCRIPTION
**Pull request by aido**
# Checklist

- [x] App update process has been followed 
- [x] Target branch is `develop` 
- [x] Application version has been bumped 

# Description
This pull request is a pre-release of v1.7.4

See discussion at aido/app-seed-tool#32 for some background.

Reliance on the `cx_bn_gf2_n_mul()` syscall has been removed in favour of the internal `bn_gf2_n_mul()` function for all devices. If this version does not have the same issues as described in aido/app-seed-tool#32 then we will know for sure that `cx_bn_gf2_n_mul()` is causing issue.

If `cx_bn_gf2_n_mul()` is shown to be the issue we can then release a v1.7.4-rc.2 that implements the suggestion from @srasoamiaramanana-ledger i.e.

> Could you try to call cx_bn_gf2_n_mul() without overlapping the variable for the result and the variables for the operand ?

### CODE REVIEW

**Comment by aido** [comment]
As an aside, I notice that the "Compilation & test" action consistently fails on every pull request due to issues with a token when uploading to codecov.io.

There may be two ways to fix this:
1. Install the [GitHub Codecov](https://github.com/apps/codecov) app for this repo
	or
2. Change the following to `false`
https://github.com/LedgerHQ/app-seed-tool/blob/f188c9fbab3e0aec3fe42f8c77d9f3e928c0bd2c/.github/workflows/ci-workflow.yml#L63

Which would you prefer?

**Comment by lpascal-ledger** [comment]
I've configured the repo with the correct Codecov token, yet it fails still `Rate limit reached. Please upload with the Codecov repository upload token to resolve issue`. Srly annoying. Maybe it'll apply once it's merged?

**Comment by lpascal-ledger** [comment]
@aido 1.7.4-rc1 was deployed on NanoS, S+ and X

**Comment by aido** [comment]
@lpascal-ledger 

> Srly annoying. Maybe it'll apply once it's merged?

The next PR will bump the Codecov GitHub action from v3 to v4. Let's see if that helps.

**Comment by lpascal-ledger** [comment]
@aido also the workflows triggered by the merge and the tag were successful, that's promising.

**Pull request merged**
